export const string = 'string'
export const number = 'number'
export const value = 'auto | number | string'
export const display = 'inline | block | inline-block | flex | inline-flex'
export const boolean = 'boolean'
export const position = 'static | relative | fixed | absolute | sticky'
export const boxSizing = 'content-box | border-box'
export const resetAll = 'unset | revert | inital | inherit'
export const objectFit =
  'fill | contain | cover | scale-down | none | initial | inherit'
export const order = 'number | initial | inherit'
export const resize = 'none | both | horizontal | vertical'
export const lineHeight = 'number | string'
export const fontSize =
  'medium | xx-small | x-small | small | large | x-large | xx-large | smaller | larger | initial | inherit'
export const fontStyle = 'normal | italic | oblique'
export const fontWeight =
  'normal | bold | bolder | lighter | 100 | 200 | 300 | 400 | 500 | 600 | 700 | 800 | 900'
export const textAlign = 'left | right | center | justify'
export const textTransform = 'none | capitalize | uppercase | lowercase'
export const letterSpacing = 'normal | string | number'
export const textOverflow = 'clip | ellipsis | string'
export const whiteSpace = 'normal | nowrap | pre | pre-line | pre-wrap'
export const wordBreak = 'normal | break-all | keep-all | break-word'
export const wordWrap = 'normal | break-word'
export const writingMode = 'horizontal-tb | vertical-rl | vertical-lr'
export const listStyleType =
  'disc | armenian | circle | cjk-ideographic | decimal | decimal-leading-zero | georgian | hebrew | hiragana | hiragana-iroha | katakana | katakana-iroha | lower-alpha | lower-greek | lower-latin | lower-roman | none | square | upper-alpha | upper-greek | upper-latin | upper-roman'
export const listStyleImage = 'none | string'
export const backgroundColor = 'transparent | string'
export const backgroundImg = 'none | string'
export const backgroundClip = 'border-box | padding-box | content-box'
export const backgroundOrigin = 'padding-box | border-box | content-box'
export const backgroundRepeat = 'repeat | repeat-x | repeat-y | no-repeat'
export const backgroundSize = 'auto | value | cover | contain | number | string'
export const borderStyle =
  'none | hidden | dotted | dashed | solid | double | groove | ridge | inset | outset'
export const borderColor = 'transparent | string'
export const overflow = 'visible | hidden | scroll | auto'
export const overflowWrap = 'normal | break-word'
export const visibility = 'visible | hidden | collapse'
export const cursor =
  'alias | all-scroll | auto | cell | context-menu | col-resize | copy | crosshair | default | e-resize | ew-resize | grab | grabbing | help | move | n-resize | ne-resize | nesw-resize | ns-resize | nw-resize | nwse-resize | no-drop | none | not-allowed | pointer | progress | row-resize | s-resize | se-resize | sw-resize | text | URL | vertical-text | w-resize | wait | zoom-in | zoom-out'
export const userSelect = 'auto | none | text | all'
export const pointerEvents = 'auto | none'
export const writingDirection = 'ltr | rtl'
export const extendCss = 'string | css function'
